services:
  mp:
    environment:
      MP_HTTP_BASE_URL: "https://dommehut.xyz"
      MP_WS_BASE_URL: "wss://dommehut.xyz"
      MP_CORS_ORIGIN: "dommehut.xyz"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mp.rule=Host(`dommehut.xyz`)"
      - "traefik.http.routers.mp.tls.certresolver=cloudflare"
      - "traefik.http.routers.mp.entrypoints=https"
      - "traefik.http.services.mp.loadbalancer.server.port=8080"
    networks:
      - traefik

  grafana:
    environment:
      - GF_SERVER_ROOT_URL=https://grafana.dommehut.xyz
    labels:
      - "traefik.http.routers.grafana.rule=Host(`grafana.dommehut.xyz`)"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.entrypoints=https"

  traefik:
    command:
      - "--api.dashboard=false"
      - "--api.debug=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--entrypoints.http.http.redirections.entryPoint.to=https"
      - "--entrypoints.http.http.redirections.entryPoint.scheme=https"
      - "--providers.docker.network=traefik"
    networks:
      - traefik

networks:
  traefik:
    external: true